FROM apache/airflow:slim-latest-python3.10

# Install the psycopg2-binary package
RUN pip install psycopg2-binary

# Copy the custom script into the Docker image
COPY airflow_after_entrypoint_script.sh /airflow_after_entrypoint_script.sh

# Ensure that the Docker container is running as the root user
USER root

# Make the custom script executable
RUN chmod +x /airflow_after_entrypoint_script.sh

# Switch back to the airflow user for security
USER airflow