name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_HOST: localhost
          POSTGRES_DB: staging_db
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_THREADS: 1
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt-postgres

      - name: Deploy to staging
        env:
          DBT_PROFILE: dbt_poc
          DBT_TARGET: cd
        run: |
          cd dbt_project
           dbt deps --profiles-dir .
           dbt seed --profiles-dir .
           dbt run --profiles-dir .
           dbt test --profiles-dir .
