name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-22.04
    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_HOST: localhost
          POSTGRES_DB: dev_db
          POSTGRES_SCHEMA: public
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_THREADS: 4
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt-postgres

      - name: Run dbt tests
        env:
          DBT_PROFILE: dbt_poc
          DBT_TARGET: ci
        run: |
          cd dbt_project
          dbt deps --profiles-dir .
          dbt seed --profiles-dir .
          dbt run --profiles-dir .
          dbt test --profiles-dir .
