name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: dev_db
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt-postgres

      - name: Run dbt tests
        run: |
          dbt deps
          dbt seed --profiles-dir dbt_project
          dbt run --profiles-dir dbt_project
          dbt test --profiles-dir dbt_project
